version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "skool"
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
