[package]
name = "skool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.19"
serde = { version = "1.0.133", features = ["derive"] }
skolplattformen = { path = "../skolplattformen" }
thiserror = "1.0.30"
futures = "0.3.19"
skool-cookie = { path = "../skool-cookie" }
actix-cors = "0.6.0-beta.8"
chrono = "0.4.19"
tracing-subscriber = "0.3.5"
dotenv = "0.15.0"
reqwest = "0.11.9"
tracing = "0.1.29"
tracing-actix-web = "0.5.0-alpha.10"
uuid = { version = "0.8.2", features = ["v4"] }
agenda = { path = "../agenda" }
mime = "0.3.16"
structopt = "0.3.26"
