[package]
name = "skool"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0.133", features = ["derive"] }
skolplattformen = { path = "../skolplattformen" }
thiserror = "1.0.31"
futures = "0.3.19"
actix-cors = "0.6.1"
chrono = "0.4.19"
tracing-subscriber = "0.3.5"
dotenv = "0.15.0"
reqwest = "0.11.10"
tracing = "0.1.29"
tracing-actix-web = "0.5.1"
uuid = { version = "0.8.2", features = ["v4"] }
skool-agenda = { path = "../agenda" }
mime = "0.3.16"
structopt = "0.3.26"
actix-web-httpauth = "0.6.0"
rmp-serde = "1.1.0"
aes-gcm-siv = "0.10.3"
rand = "0.8.5"
base64 = "0.13.0"
hex = "0.4.3"
