[package]
name = "skool"
version = "0.3.3"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
serde = { version = "1.0.145", features = ["derive"] }
skolplattformen = { path = "../skolplattformen" }
thiserror = "1.0.37"
futures = "0.3.19"
actix-cors = "0.6.1"
chrono = "0.4.22"
tracing-subscriber = "0.3.5"
dotenv = "0.15.0"
reqwest = "0.11.10"
tracing = "0.1.29"
uuid = { version = "1.1.2", features = ["v4"] }
skool-agenda = { path = "../agenda" }
mime = "0.3.16"
auth1-sdk = { git = "https://github.com/skolorna/auth1", branch = "develop", version = "0.1.1", features = ["actix"] }
sqlx = { version = "0.6.2", features = ["runtime-actix-rustls", "postgres", "uuid", "chrono", "offline"] }
clap = { version = "4.0.18", features = ["derive", "env"] }
aes-gcm-siv = "0.11.1"
rmp-serde = "1.1.0"
hex = "0.4.3"
rand = "0.8.5"
sentry = "0.27.0"
sentry-actix = "0.27.0"
deadpool-redis = "0.10.2"
