language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

sudo: false

script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features

notifications:
  email:
    on_success: never
